baseurl = "https://www.sslife.tech/"
languageCode = "ja"
title = "SSLife Tech"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; sslife.tech Copyright"
theme = 'vienna'
enableEmoji = true
uglyURLs = true
hrefTargetBlank = true
rssLimit = 10

[params]
    featured_image = "/images/ogp.jpg"
    image = "/images/bg.jpg"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    # bio = ""
    subtitle = "しょうちゃんとしおりんのブログ"
    description = "しょうちゃんとしおりんのブログ"
    themecolor = "#0288d1" # Defines the tab color in Chrome for Android.
