version: 2.1

jobs:
  build:
    working_directory: &working_directory ~/workspace
    docker:
      - image: circleci/golang:1.12.1
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache:
          name: Restore go modules cache
          keys:
            - mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
      - run:
          name: Install dependencies
          command: go mod download
      - run:
          name: Install hugo
          command: go get github.com/gohugoio/hugo
      - save_cache:
          name: Save go modules cache
          key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod/cache
      - run:
          name:
          command: git submodule sync
      - run:
          name: Update submodules
          command: git submodule update --init
      - run:
          name: Build
          command: HUGO_ENV=production hugo
      - persist_to_workspace:
          root: .
          paths:
            - public
            - .firebaserc
            - firebase.json
            - package.json
            - yarn.lock
  deploy:
    working_directory: *working_directory
    docker:
      - image: circleci/node:11
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore yarn dependencies
          keys:
            - yarn-node-11-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --production=false
      - save_cache:
          name: Save yarn dependencies
          key: yarn-node-11-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Minify
          command: yarn minify
      - deploy:
          command: yarn deploy --only hosting --token ${FIREBASE_TOKEN}
workflows:
  version: 2
  default:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
