version: 2.1

orbs:
  hugo: circleci/hugo@0.3.1

jobs:
  deploy:
    working_directory:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore yarn dependencies
          keys:
            - yarn-node-12-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --production=false
      - save_cache:
          name: Save yarn dependencies
          key: yarn-node-12-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Minify
          command: yarn minify
      - deploy:
          command: yarn deploy --only hosting --token ${FIREBASE_TOKEN}

workflows:
  default:
    jobs:
      - hugo/build:
          # 速度最適化のため、imgタグにsrcなどを入れていない。
          # そのためhtml-prooferを実行するとCIが落ちるためoffにしている
          html-proofer: false
      - deploy:
          requires:
            - hugo/build
          filters:
            branches:
              only: master
